// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf_examples/protos/person.proto

package person;

public final class PersonOuterClass {
  private PersonOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code person.EyeColor}
   */
  public enum EyeColor
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOW_EYE_COLOR = 0;</code>
     */
    UNKNOW_EYE_COLOR(0),
    /**
     * <code>EYE_GREEN = 1;</code>
     */
    EYE_GREEN(1),
    /**
     * <code>EYE_BROWN = 2;</code>
     */
    EYE_BROWN(2),
    /**
     * <code>EYE_BLUE = 3;</code>
     */
    EYE_BLUE(3),
    /**
     * <code>EYE_BLACK = 4;</code>
     */
    EYE_BLACK(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOW_EYE_COLOR = 0;</code>
     */
    public static final int UNKNOW_EYE_COLOR_VALUE = 0;
    /**
     * <code>EYE_GREEN = 1;</code>
     */
    public static final int EYE_GREEN_VALUE = 1;
    /**
     * <code>EYE_BROWN = 2;</code>
     */
    public static final int EYE_BROWN_VALUE = 2;
    /**
     * <code>EYE_BLUE = 3;</code>
     */
    public static final int EYE_BLUE_VALUE = 3;
    /**
     * <code>EYE_BLACK = 4;</code>
     */
    public static final int EYE_BLACK_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EyeColor valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EyeColor forNumber(int value) {
      switch (value) {
        case 0: return UNKNOW_EYE_COLOR;
        case 1: return EYE_GREEN;
        case 2: return EYE_BROWN;
        case 3: return EYE_BLUE;
        case 4: return EYE_BLACK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EyeColor>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EyeColor> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EyeColor>() {
            public EyeColor findValueByNumber(int number) {
              return EyeColor.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return person.PersonOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final EyeColor[] VALUES = values();

    public static EyeColor valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EyeColor(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:person.EyeColor)
  }

  public interface MyMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:person.MyMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string first_name = 2;</code>
     * @return The firstName.
     */
    java.lang.String getFirstName();
    /**
     * <code>string first_name = 2;</code>
     * @return The bytes for firstName.
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>bool is_validated = 3;</code>
     * @return The isValidated.
     */
    boolean getIsValidated();
  }
  /**
   * Protobuf type {@code person.MyMessage}
   */
  public static final class MyMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:person.MyMessage)
      MyMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MyMessage.newBuilder() to construct.
    private MyMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MyMessage() {
      firstName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MyMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MyMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              firstName_ = s;
              break;
            }
            case 24: {

              isValidated_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return person.PersonOuterClass.internal_static_person_MyMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return person.PersonOuterClass.internal_static_person_MyMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              person.PersonOuterClass.MyMessage.class, person.PersonOuterClass.MyMessage.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int FIRST_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object firstName_;
    /**
     * <code>string first_name = 2;</code>
     * @return The firstName.
     */
    @java.lang.Override
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      }
    }
    /**
     * <code>string first_name = 2;</code>
     * @return The bytes for firstName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IS_VALIDATED_FIELD_NUMBER = 3;
    private boolean isValidated_;
    /**
     * <code>bool is_validated = 3;</code>
     * @return The isValidated.
     */
    @java.lang.Override
    public boolean getIsValidated() {
      return isValidated_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, firstName_);
      }
      if (isValidated_ != false) {
        output.writeBool(3, isValidated_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, firstName_);
      }
      if (isValidated_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isValidated_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof person.PersonOuterClass.MyMessage)) {
        return super.equals(obj);
      }
      person.PersonOuterClass.MyMessage other = (person.PersonOuterClass.MyMessage) obj;

      if (getId()
          != other.getId()) return false;
      if (!getFirstName()
          .equals(other.getFirstName())) return false;
      if (getIsValidated()
          != other.getIsValidated()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + FIRST_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
      hash = (37 * hash) + IS_VALIDATED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsValidated());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static person.PersonOuterClass.MyMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static person.PersonOuterClass.MyMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static person.PersonOuterClass.MyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static person.PersonOuterClass.MyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static person.PersonOuterClass.MyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static person.PersonOuterClass.MyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static person.PersonOuterClass.MyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static person.PersonOuterClass.MyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static person.PersonOuterClass.MyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static person.PersonOuterClass.MyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static person.PersonOuterClass.MyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static person.PersonOuterClass.MyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(person.PersonOuterClass.MyMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code person.MyMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:person.MyMessage)
        person.PersonOuterClass.MyMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return person.PersonOuterClass.internal_static_person_MyMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return person.PersonOuterClass.internal_static_person_MyMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                person.PersonOuterClass.MyMessage.class, person.PersonOuterClass.MyMessage.Builder.class);
      }

      // Construct using person.PersonOuterClass.MyMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        firstName_ = "";

        isValidated_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return person.PersonOuterClass.internal_static_person_MyMessage_descriptor;
      }

      @java.lang.Override
      public person.PersonOuterClass.MyMessage getDefaultInstanceForType() {
        return person.PersonOuterClass.MyMessage.getDefaultInstance();
      }

      @java.lang.Override
      public person.PersonOuterClass.MyMessage build() {
        person.PersonOuterClass.MyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public person.PersonOuterClass.MyMessage buildPartial() {
        person.PersonOuterClass.MyMessage result = new person.PersonOuterClass.MyMessage(this);
        result.id_ = id_;
        result.firstName_ = firstName_;
        result.isValidated_ = isValidated_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof person.PersonOuterClass.MyMessage) {
          return mergeFrom((person.PersonOuterClass.MyMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(person.PersonOuterClass.MyMessage other) {
        if (other == person.PersonOuterClass.MyMessage.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getFirstName().isEmpty()) {
          firstName_ = other.firstName_;
          onChanged();
        }
        if (other.getIsValidated() != false) {
          setIsValidated(other.getIsValidated());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        person.PersonOuterClass.MyMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (person.PersonOuterClass.MyMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object firstName_ = "";
      /**
       * <code>string first_name = 2;</code>
       * @return The firstName.
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string first_name = 2;</code>
       * @return The bytes for firstName.
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string first_name = 2;</code>
       * @param value The firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string first_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstName() {
        
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>string first_name = 2;</code>
       * @param value The bytes for firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        firstName_ = value;
        onChanged();
        return this;
      }

      private boolean isValidated_ ;
      /**
       * <code>bool is_validated = 3;</code>
       * @return The isValidated.
       */
      @java.lang.Override
      public boolean getIsValidated() {
        return isValidated_;
      }
      /**
       * <code>bool is_validated = 3;</code>
       * @param value The isValidated to set.
       * @return This builder for chaining.
       */
      public Builder setIsValidated(boolean value) {
        
        isValidated_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_validated = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsValidated() {
        
        isValidated_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:person.MyMessage)
    }

    // @@protoc_insertion_point(class_scope:person.MyMessage)
    private static final person.PersonOuterClass.MyMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new person.PersonOuterClass.MyMessage();
    }

    public static person.PersonOuterClass.MyMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MyMessage>
        PARSER = new com.google.protobuf.AbstractParser<MyMessage>() {
      @java.lang.Override
      public MyMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MyMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MyMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MyMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public person.PersonOuterClass.MyMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:person.Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * the age of the person 
     * </pre>
     *
     * <code>int32 age = 1;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <pre>
     * as documented
     * </pre>
     *
     * <code>string first_name = 2;</code>
     * @return The firstName.
     */
    java.lang.String getFirstName();
    /**
     * <pre>
     * as documented
     * </pre>
     *
     * <code>string first_name = 2;</code>
     * @return The bytes for firstName.
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <pre>
     * as documented
     * </pre>
     *
     * <code>string last_name = 3;</code>
     * @return The lastName.
     */
    java.lang.String getLastName();
    /**
     * <pre>
     * as documented
     * </pre>
     *
     * <code>string last_name = 3;</code>
     * @return The bytes for lastName.
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <pre>
     * small picture represents a small .jpg file
     * </pre>
     *
     * <code>bytes small_picture = 4;</code>
     * @return The smallPicture.
     */
    com.google.protobuf.ByteString getSmallPicture();

    /**
     * <code>bool is_verified = 5;</code>
     * @return The isVerified.
     */
    boolean getIsVerified();

    /**
     * <pre>
     * height of the person in cms
     * </pre>
     *
     * <code>float height = 6;</code>
     * @return The height.
     */
    float getHeight();

    /**
     * <pre>
     * a list of phone numbers provided in signup form.
     * </pre>
     *
     * <code>repeated string phone_numbers = 7;</code>
     * @return A list containing the phoneNumbers.
     */
    java.util.List<java.lang.String>
        getPhoneNumbersList();
    /**
     * <pre>
     * a list of phone numbers provided in signup form.
     * </pre>
     *
     * <code>repeated string phone_numbers = 7;</code>
     * @return The count of phoneNumbers.
     */
    int getPhoneNumbersCount();
    /**
     * <pre>
     * a list of phone numbers provided in signup form.
     * </pre>
     *
     * <code>repeated string phone_numbers = 7;</code>
     * @param index The index of the element to return.
     * @return The phoneNumbers at the given index.
     */
    java.lang.String getPhoneNumbers(int index);
    /**
     * <pre>
     * a list of phone numbers provided in signup form.
     * </pre>
     *
     * <code>repeated string phone_numbers = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the phoneNumbers at the given index.
     */
    com.google.protobuf.ByteString
        getPhoneNumbersBytes(int index);

    /**
     * <pre>
     * enum
     * </pre>
     *
     * <code>.person.EyeColor eye_color = 8;</code>
     * @return The enum numeric value on the wire for eyeColor.
     */
    int getEyeColorValue();
    /**
     * <pre>
     * enum
     * </pre>
     *
     * <code>.person.EyeColor eye_color = 8;</code>
     * @return The eyeColor.
     */
    person.PersonOuterClass.EyeColor getEyeColor();

    /**
     * <pre>
     * birthday
     * </pre>
     *
     * <code>.Date birthday = 9;</code>
     * @return Whether the birthday field is set.
     */
    boolean hasBirthday();
    /**
     * <pre>
     * birthday
     * </pre>
     *
     * <code>.Date birthday = 9;</code>
     * @return The birthday.
     */
    DateOuterClass.Date getBirthday();
    /**
     * <pre>
     * birthday
     * </pre>
     *
     * <code>.Date birthday = 9;</code>
     */
    DateOuterClass.DateOrBuilder getBirthdayOrBuilder();

    /**
     * <pre>
     * multiple addresses
     * </pre>
     *
     * <code>repeated .person.address.Address addresses = 10;</code>
     */
    java.util.List<person.address.AddressOuterClass.Address> 
        getAddressesList();
    /**
     * <pre>
     * multiple addresses
     * </pre>
     *
     * <code>repeated .person.address.Address addresses = 10;</code>
     */
    person.address.AddressOuterClass.Address getAddresses(int index);
    /**
     * <pre>
     * multiple addresses
     * </pre>
     *
     * <code>repeated .person.address.Address addresses = 10;</code>
     */
    int getAddressesCount();
    /**
     * <pre>
     * multiple addresses
     * </pre>
     *
     * <code>repeated .person.address.Address addresses = 10;</code>
     */
    java.util.List<? extends person.address.AddressOuterClass.AddressOrBuilder> 
        getAddressesOrBuilderList();
    /**
     * <pre>
     * multiple addresses
     * </pre>
     *
     * <code>repeated .person.address.Address addresses = 10;</code>
     */
    person.address.AddressOuterClass.AddressOrBuilder getAddressesOrBuilder(
        int index);
  }
  /**
   * <pre>
   * Person is used to identify users 
   * across our system 
   * </pre>
   *
   * Protobuf type {@code person.Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:person.Person)
      PersonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      firstName_ = "";
      lastName_ = "";
      smallPicture_ = com.google.protobuf.ByteString.EMPTY;
      phoneNumbers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      eyeColor_ = 0;
      addresses_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Person();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              age_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              firstName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              lastName_ = s;
              break;
            }
            case 34: {

              smallPicture_ = input.readBytes();
              break;
            }
            case 40: {

              isVerified_ = input.readBool();
              break;
            }
            case 53: {

              height_ = input.readFloat();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                phoneNumbers_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              phoneNumbers_.add(s);
              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              eyeColor_ = rawValue;
              break;
            }
            case 74: {
              DateOuterClass.Date.Builder subBuilder = null;
              if (birthday_ != null) {
                subBuilder = birthday_.toBuilder();
              }
              birthday_ = input.readMessage(DateOuterClass.Date.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(birthday_);
                birthday_ = subBuilder.buildPartial();
              }

              break;
            }
            case 82: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                addresses_ = new java.util.ArrayList<person.address.AddressOuterClass.Address>();
                mutable_bitField0_ |= 0x00000002;
              }
              addresses_.add(
                  input.readMessage(person.address.AddressOuterClass.Address.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          phoneNumbers_ = phoneNumbers_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          addresses_ = java.util.Collections.unmodifiableList(addresses_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return person.PersonOuterClass.internal_static_person_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return person.PersonOuterClass.internal_static_person_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              person.PersonOuterClass.Person.class, person.PersonOuterClass.Person.Builder.class);
    }

    public static final int AGE_FIELD_NUMBER = 1;
    private int age_;
    /**
     * <pre>
     * the age of the person 
     * </pre>
     *
     * <code>int32 age = 1;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }

    public static final int FIRST_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object firstName_;
    /**
     * <pre>
     * as documented
     * </pre>
     *
     * <code>string first_name = 2;</code>
     * @return The firstName.
     */
    @java.lang.Override
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * as documented
     * </pre>
     *
     * <code>string first_name = 2;</code>
     * @return The bytes for firstName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object lastName_;
    /**
     * <pre>
     * as documented
     * </pre>
     *
     * <code>string last_name = 3;</code>
     * @return The lastName.
     */
    @java.lang.Override
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * as documented
     * </pre>
     *
     * <code>string last_name = 3;</code>
     * @return The bytes for lastName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SMALL_PICTURE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString smallPicture_;
    /**
     * <pre>
     * small picture represents a small .jpg file
     * </pre>
     *
     * <code>bytes small_picture = 4;</code>
     * @return The smallPicture.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSmallPicture() {
      return smallPicture_;
    }

    public static final int IS_VERIFIED_FIELD_NUMBER = 5;
    private boolean isVerified_;
    /**
     * <code>bool is_verified = 5;</code>
     * @return The isVerified.
     */
    @java.lang.Override
    public boolean getIsVerified() {
      return isVerified_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 6;
    private float height_;
    /**
     * <pre>
     * height of the person in cms
     * </pre>
     *
     * <code>float height = 6;</code>
     * @return The height.
     */
    @java.lang.Override
    public float getHeight() {
      return height_;
    }

    public static final int PHONE_NUMBERS_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList phoneNumbers_;
    /**
     * <pre>
     * a list of phone numbers provided in signup form.
     * </pre>
     *
     * <code>repeated string phone_numbers = 7;</code>
     * @return A list containing the phoneNumbers.
     */
    public com.google.protobuf.ProtocolStringList
        getPhoneNumbersList() {
      return phoneNumbers_;
    }
    /**
     * <pre>
     * a list of phone numbers provided in signup form.
     * </pre>
     *
     * <code>repeated string phone_numbers = 7;</code>
     * @return The count of phoneNumbers.
     */
    public int getPhoneNumbersCount() {
      return phoneNumbers_.size();
    }
    /**
     * <pre>
     * a list of phone numbers provided in signup form.
     * </pre>
     *
     * <code>repeated string phone_numbers = 7;</code>
     * @param index The index of the element to return.
     * @return The phoneNumbers at the given index.
     */
    public java.lang.String getPhoneNumbers(int index) {
      return phoneNumbers_.get(index);
    }
    /**
     * <pre>
     * a list of phone numbers provided in signup form.
     * </pre>
     *
     * <code>repeated string phone_numbers = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the phoneNumbers at the given index.
     */
    public com.google.protobuf.ByteString
        getPhoneNumbersBytes(int index) {
      return phoneNumbers_.getByteString(index);
    }

    public static final int EYE_COLOR_FIELD_NUMBER = 8;
    private int eyeColor_;
    /**
     * <pre>
     * enum
     * </pre>
     *
     * <code>.person.EyeColor eye_color = 8;</code>
     * @return The enum numeric value on the wire for eyeColor.
     */
    @java.lang.Override public int getEyeColorValue() {
      return eyeColor_;
    }
    /**
     * <pre>
     * enum
     * </pre>
     *
     * <code>.person.EyeColor eye_color = 8;</code>
     * @return The eyeColor.
     */
    @java.lang.Override public person.PersonOuterClass.EyeColor getEyeColor() {
      @SuppressWarnings("deprecation")
      person.PersonOuterClass.EyeColor result = person.PersonOuterClass.EyeColor.valueOf(eyeColor_);
      return result == null ? person.PersonOuterClass.EyeColor.UNRECOGNIZED : result;
    }

    public static final int BIRTHDAY_FIELD_NUMBER = 9;
    private DateOuterClass.Date birthday_;
    /**
     * <pre>
     * birthday
     * </pre>
     *
     * <code>.Date birthday = 9;</code>
     * @return Whether the birthday field is set.
     */
    @java.lang.Override
    public boolean hasBirthday() {
      return birthday_ != null;
    }
    /**
     * <pre>
     * birthday
     * </pre>
     *
     * <code>.Date birthday = 9;</code>
     * @return The birthday.
     */
    @java.lang.Override
    public DateOuterClass.Date getBirthday() {
      return birthday_ == null ? DateOuterClass.Date.getDefaultInstance() : birthday_;
    }
    /**
     * <pre>
     * birthday
     * </pre>
     *
     * <code>.Date birthday = 9;</code>
     */
    @java.lang.Override
    public DateOuterClass.DateOrBuilder getBirthdayOrBuilder() {
      return getBirthday();
    }

    public static final int ADDRESSES_FIELD_NUMBER = 10;
    private java.util.List<person.address.AddressOuterClass.Address> addresses_;
    /**
     * <pre>
     * multiple addresses
     * </pre>
     *
     * <code>repeated .person.address.Address addresses = 10;</code>
     */
    @java.lang.Override
    public java.util.List<person.address.AddressOuterClass.Address> getAddressesList() {
      return addresses_;
    }
    /**
     * <pre>
     * multiple addresses
     * </pre>
     *
     * <code>repeated .person.address.Address addresses = 10;</code>
     */
    @java.lang.Override
    public java.util.List<? extends person.address.AddressOuterClass.AddressOrBuilder> 
        getAddressesOrBuilderList() {
      return addresses_;
    }
    /**
     * <pre>
     * multiple addresses
     * </pre>
     *
     * <code>repeated .person.address.Address addresses = 10;</code>
     */
    @java.lang.Override
    public int getAddressesCount() {
      return addresses_.size();
    }
    /**
     * <pre>
     * multiple addresses
     * </pre>
     *
     * <code>repeated .person.address.Address addresses = 10;</code>
     */
    @java.lang.Override
    public person.address.AddressOuterClass.Address getAddresses(int index) {
      return addresses_.get(index);
    }
    /**
     * <pre>
     * multiple addresses
     * </pre>
     *
     * <code>repeated .person.address.Address addresses = 10;</code>
     */
    @java.lang.Override
    public person.address.AddressOuterClass.AddressOrBuilder getAddressesOrBuilder(
        int index) {
      return addresses_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (age_ != 0) {
        output.writeInt32(1, age_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lastName_);
      }
      if (!smallPicture_.isEmpty()) {
        output.writeBytes(4, smallPicture_);
      }
      if (isVerified_ != false) {
        output.writeBool(5, isVerified_);
      }
      if (height_ != 0F) {
        output.writeFloat(6, height_);
      }
      for (int i = 0; i < phoneNumbers_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, phoneNumbers_.getRaw(i));
      }
      if (eyeColor_ != person.PersonOuterClass.EyeColor.UNKNOW_EYE_COLOR.getNumber()) {
        output.writeEnum(8, eyeColor_);
      }
      if (birthday_ != null) {
        output.writeMessage(9, getBirthday());
      }
      for (int i = 0; i < addresses_.size(); i++) {
        output.writeMessage(10, addresses_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, age_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lastName_);
      }
      if (!smallPicture_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, smallPicture_);
      }
      if (isVerified_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isVerified_);
      }
      if (height_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, height_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < phoneNumbers_.size(); i++) {
          dataSize += computeStringSizeNoTag(phoneNumbers_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPhoneNumbersList().size();
      }
      if (eyeColor_ != person.PersonOuterClass.EyeColor.UNKNOW_EYE_COLOR.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, eyeColor_);
      }
      if (birthday_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, getBirthday());
      }
      for (int i = 0; i < addresses_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, addresses_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof person.PersonOuterClass.Person)) {
        return super.equals(obj);
      }
      person.PersonOuterClass.Person other = (person.PersonOuterClass.Person) obj;

      if (getAge()
          != other.getAge()) return false;
      if (!getFirstName()
          .equals(other.getFirstName())) return false;
      if (!getLastName()
          .equals(other.getLastName())) return false;
      if (!getSmallPicture()
          .equals(other.getSmallPicture())) return false;
      if (getIsVerified()
          != other.getIsVerified()) return false;
      if (java.lang.Float.floatToIntBits(getHeight())
          != java.lang.Float.floatToIntBits(
              other.getHeight())) return false;
      if (!getPhoneNumbersList()
          .equals(other.getPhoneNumbersList())) return false;
      if (eyeColor_ != other.eyeColor_) return false;
      if (hasBirthday() != other.hasBirthday()) return false;
      if (hasBirthday()) {
        if (!getBirthday()
            .equals(other.getBirthday())) return false;
      }
      if (!getAddressesList()
          .equals(other.getAddressesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + FIRST_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
      hash = (37 * hash) + LAST_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
      hash = (37 * hash) + SMALL_PICTURE_FIELD_NUMBER;
      hash = (53 * hash) + getSmallPicture().hashCode();
      hash = (37 * hash) + IS_VERIFIED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsVerified());
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getHeight());
      if (getPhoneNumbersCount() > 0) {
        hash = (37 * hash) + PHONE_NUMBERS_FIELD_NUMBER;
        hash = (53 * hash) + getPhoneNumbersList().hashCode();
      }
      hash = (37 * hash) + EYE_COLOR_FIELD_NUMBER;
      hash = (53 * hash) + eyeColor_;
      if (hasBirthday()) {
        hash = (37 * hash) + BIRTHDAY_FIELD_NUMBER;
        hash = (53 * hash) + getBirthday().hashCode();
      }
      if (getAddressesCount() > 0) {
        hash = (37 * hash) + ADDRESSES_FIELD_NUMBER;
        hash = (53 * hash) + getAddressesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static person.PersonOuterClass.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static person.PersonOuterClass.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static person.PersonOuterClass.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static person.PersonOuterClass.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static person.PersonOuterClass.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static person.PersonOuterClass.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static person.PersonOuterClass.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static person.PersonOuterClass.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static person.PersonOuterClass.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static person.PersonOuterClass.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static person.PersonOuterClass.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static person.PersonOuterClass.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(person.PersonOuterClass.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Person is used to identify users 
     * across our system 
     * </pre>
     *
     * Protobuf type {@code person.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:person.Person)
        person.PersonOuterClass.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return person.PersonOuterClass.internal_static_person_Person_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return person.PersonOuterClass.internal_static_person_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                person.PersonOuterClass.Person.class, person.PersonOuterClass.Person.Builder.class);
      }

      // Construct using person.PersonOuterClass.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAddressesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        age_ = 0;

        firstName_ = "";

        lastName_ = "";

        smallPicture_ = com.google.protobuf.ByteString.EMPTY;

        isVerified_ = false;

        height_ = 0F;

        phoneNumbers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        eyeColor_ = 0;

        if (birthdayBuilder_ == null) {
          birthday_ = null;
        } else {
          birthday_ = null;
          birthdayBuilder_ = null;
        }
        if (addressesBuilder_ == null) {
          addresses_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          addressesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return person.PersonOuterClass.internal_static_person_Person_descriptor;
      }

      @java.lang.Override
      public person.PersonOuterClass.Person getDefaultInstanceForType() {
        return person.PersonOuterClass.Person.getDefaultInstance();
      }

      @java.lang.Override
      public person.PersonOuterClass.Person build() {
        person.PersonOuterClass.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public person.PersonOuterClass.Person buildPartial() {
        person.PersonOuterClass.Person result = new person.PersonOuterClass.Person(this);
        int from_bitField0_ = bitField0_;
        result.age_ = age_;
        result.firstName_ = firstName_;
        result.lastName_ = lastName_;
        result.smallPicture_ = smallPicture_;
        result.isVerified_ = isVerified_;
        result.height_ = height_;
        if (((bitField0_ & 0x00000001) != 0)) {
          phoneNumbers_ = phoneNumbers_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.phoneNumbers_ = phoneNumbers_;
        result.eyeColor_ = eyeColor_;
        if (birthdayBuilder_ == null) {
          result.birthday_ = birthday_;
        } else {
          result.birthday_ = birthdayBuilder_.build();
        }
        if (addressesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            addresses_ = java.util.Collections.unmodifiableList(addresses_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.addresses_ = addresses_;
        } else {
          result.addresses_ = addressesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof person.PersonOuterClass.Person) {
          return mergeFrom((person.PersonOuterClass.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(person.PersonOuterClass.Person other) {
        if (other == person.PersonOuterClass.Person.getDefaultInstance()) return this;
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (!other.getFirstName().isEmpty()) {
          firstName_ = other.firstName_;
          onChanged();
        }
        if (!other.getLastName().isEmpty()) {
          lastName_ = other.lastName_;
          onChanged();
        }
        if (other.getSmallPicture() != com.google.protobuf.ByteString.EMPTY) {
          setSmallPicture(other.getSmallPicture());
        }
        if (other.getIsVerified() != false) {
          setIsVerified(other.getIsVerified());
        }
        if (other.getHeight() != 0F) {
          setHeight(other.getHeight());
        }
        if (!other.phoneNumbers_.isEmpty()) {
          if (phoneNumbers_.isEmpty()) {
            phoneNumbers_ = other.phoneNumbers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePhoneNumbersIsMutable();
            phoneNumbers_.addAll(other.phoneNumbers_);
          }
          onChanged();
        }
        if (other.eyeColor_ != 0) {
          setEyeColorValue(other.getEyeColorValue());
        }
        if (other.hasBirthday()) {
          mergeBirthday(other.getBirthday());
        }
        if (addressesBuilder_ == null) {
          if (!other.addresses_.isEmpty()) {
            if (addresses_.isEmpty()) {
              addresses_ = other.addresses_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureAddressesIsMutable();
              addresses_.addAll(other.addresses_);
            }
            onChanged();
          }
        } else {
          if (!other.addresses_.isEmpty()) {
            if (addressesBuilder_.isEmpty()) {
              addressesBuilder_.dispose();
              addressesBuilder_ = null;
              addresses_ = other.addresses_;
              bitField0_ = (bitField0_ & ~0x00000002);
              addressesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAddressesFieldBuilder() : null;
            } else {
              addressesBuilder_.addAllMessages(other.addresses_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        person.PersonOuterClass.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (person.PersonOuterClass.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int age_ ;
      /**
       * <pre>
       * the age of the person 
       * </pre>
       *
       * <code>int32 age = 1;</code>
       * @return The age.
       */
      @java.lang.Override
      public int getAge() {
        return age_;
      }
      /**
       * <pre>
       * the age of the person 
       * </pre>
       *
       * <code>int32 age = 1;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the age of the person 
       * </pre>
       *
       * <code>int32 age = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object firstName_ = "";
      /**
       * <pre>
       * as documented
       * </pre>
       *
       * <code>string first_name = 2;</code>
       * @return The firstName.
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * as documented
       * </pre>
       *
       * <code>string first_name = 2;</code>
       * @return The bytes for firstName.
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * as documented
       * </pre>
       *
       * <code>string first_name = 2;</code>
       * @param value The firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * as documented
       * </pre>
       *
       * <code>string first_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstName() {
        
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * as documented
       * </pre>
       *
       * <code>string first_name = 2;</code>
       * @param value The bytes for firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        firstName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <pre>
       * as documented
       * </pre>
       *
       * <code>string last_name = 3;</code>
       * @return The lastName.
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * as documented
       * </pre>
       *
       * <code>string last_name = 3;</code>
       * @return The bytes for lastName.
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * as documented
       * </pre>
       *
       * <code>string last_name = 3;</code>
       * @param value The lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * as documented
       * </pre>
       *
       * <code>string last_name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastName() {
        
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * as documented
       * </pre>
       *
       * <code>string last_name = 3;</code>
       * @param value The bytes for lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString smallPicture_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * small picture represents a small .jpg file
       * </pre>
       *
       * <code>bytes small_picture = 4;</code>
       * @return The smallPicture.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getSmallPicture() {
        return smallPicture_;
      }
      /**
       * <pre>
       * small picture represents a small .jpg file
       * </pre>
       *
       * <code>bytes small_picture = 4;</code>
       * @param value The smallPicture to set.
       * @return This builder for chaining.
       */
      public Builder setSmallPicture(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        smallPicture_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * small picture represents a small .jpg file
       * </pre>
       *
       * <code>bytes small_picture = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSmallPicture() {
        
        smallPicture_ = getDefaultInstance().getSmallPicture();
        onChanged();
        return this;
      }

      private boolean isVerified_ ;
      /**
       * <code>bool is_verified = 5;</code>
       * @return The isVerified.
       */
      @java.lang.Override
      public boolean getIsVerified() {
        return isVerified_;
      }
      /**
       * <code>bool is_verified = 5;</code>
       * @param value The isVerified to set.
       * @return This builder for chaining.
       */
      public Builder setIsVerified(boolean value) {
        
        isVerified_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_verified = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsVerified() {
        
        isVerified_ = false;
        onChanged();
        return this;
      }

      private float height_ ;
      /**
       * <pre>
       * height of the person in cms
       * </pre>
       *
       * <code>float height = 6;</code>
       * @return The height.
       */
      @java.lang.Override
      public float getHeight() {
        return height_;
      }
      /**
       * <pre>
       * height of the person in cms
       * </pre>
       *
       * <code>float height = 6;</code>
       * @param value The height to set.
       * @return This builder for chaining.
       */
      public Builder setHeight(float value) {
        
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * height of the person in cms
       * </pre>
       *
       * <code>float height = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeight() {
        
        height_ = 0F;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList phoneNumbers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePhoneNumbersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          phoneNumbers_ = new com.google.protobuf.LazyStringArrayList(phoneNumbers_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * a list of phone numbers provided in signup form.
       * </pre>
       *
       * <code>repeated string phone_numbers = 7;</code>
       * @return A list containing the phoneNumbers.
       */
      public com.google.protobuf.ProtocolStringList
          getPhoneNumbersList() {
        return phoneNumbers_.getUnmodifiableView();
      }
      /**
       * <pre>
       * a list of phone numbers provided in signup form.
       * </pre>
       *
       * <code>repeated string phone_numbers = 7;</code>
       * @return The count of phoneNumbers.
       */
      public int getPhoneNumbersCount() {
        return phoneNumbers_.size();
      }
      /**
       * <pre>
       * a list of phone numbers provided in signup form.
       * </pre>
       *
       * <code>repeated string phone_numbers = 7;</code>
       * @param index The index of the element to return.
       * @return The phoneNumbers at the given index.
       */
      public java.lang.String getPhoneNumbers(int index) {
        return phoneNumbers_.get(index);
      }
      /**
       * <pre>
       * a list of phone numbers provided in signup form.
       * </pre>
       *
       * <code>repeated string phone_numbers = 7;</code>
       * @param index The index of the value to return.
       * @return The bytes of the phoneNumbers at the given index.
       */
      public com.google.protobuf.ByteString
          getPhoneNumbersBytes(int index) {
        return phoneNumbers_.getByteString(index);
      }
      /**
       * <pre>
       * a list of phone numbers provided in signup form.
       * </pre>
       *
       * <code>repeated string phone_numbers = 7;</code>
       * @param index The index to set the value at.
       * @param value The phoneNumbers to set.
       * @return This builder for chaining.
       */
      public Builder setPhoneNumbers(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePhoneNumbersIsMutable();
        phoneNumbers_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * a list of phone numbers provided in signup form.
       * </pre>
       *
       * <code>repeated string phone_numbers = 7;</code>
       * @param value The phoneNumbers to add.
       * @return This builder for chaining.
       */
      public Builder addPhoneNumbers(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePhoneNumbersIsMutable();
        phoneNumbers_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * a list of phone numbers provided in signup form.
       * </pre>
       *
       * <code>repeated string phone_numbers = 7;</code>
       * @param values The phoneNumbers to add.
       * @return This builder for chaining.
       */
      public Builder addAllPhoneNumbers(
          java.lang.Iterable<java.lang.String> values) {
        ensurePhoneNumbersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, phoneNumbers_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * a list of phone numbers provided in signup form.
       * </pre>
       *
       * <code>repeated string phone_numbers = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearPhoneNumbers() {
        phoneNumbers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * a list of phone numbers provided in signup form.
       * </pre>
       *
       * <code>repeated string phone_numbers = 7;</code>
       * @param value The bytes of the phoneNumbers to add.
       * @return This builder for chaining.
       */
      public Builder addPhoneNumbersBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensurePhoneNumbersIsMutable();
        phoneNumbers_.add(value);
        onChanged();
        return this;
      }

      private int eyeColor_ = 0;
      /**
       * <pre>
       * enum
       * </pre>
       *
       * <code>.person.EyeColor eye_color = 8;</code>
       * @return The enum numeric value on the wire for eyeColor.
       */
      @java.lang.Override public int getEyeColorValue() {
        return eyeColor_;
      }
      /**
       * <pre>
       * enum
       * </pre>
       *
       * <code>.person.EyeColor eye_color = 8;</code>
       * @param value The enum numeric value on the wire for eyeColor to set.
       * @return This builder for chaining.
       */
      public Builder setEyeColorValue(int value) {
        
        eyeColor_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * enum
       * </pre>
       *
       * <code>.person.EyeColor eye_color = 8;</code>
       * @return The eyeColor.
       */
      @java.lang.Override
      public person.PersonOuterClass.EyeColor getEyeColor() {
        @SuppressWarnings("deprecation")
        person.PersonOuterClass.EyeColor result = person.PersonOuterClass.EyeColor.valueOf(eyeColor_);
        return result == null ? person.PersonOuterClass.EyeColor.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * enum
       * </pre>
       *
       * <code>.person.EyeColor eye_color = 8;</code>
       * @param value The eyeColor to set.
       * @return This builder for chaining.
       */
      public Builder setEyeColor(person.PersonOuterClass.EyeColor value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        eyeColor_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * enum
       * </pre>
       *
       * <code>.person.EyeColor eye_color = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearEyeColor() {
        
        eyeColor_ = 0;
        onChanged();
        return this;
      }

      private DateOuterClass.Date birthday_;
      private com.google.protobuf.SingleFieldBuilderV3<
          DateOuterClass.Date, DateOuterClass.Date.Builder, DateOuterClass.DateOrBuilder> birthdayBuilder_;
      /**
       * <pre>
       * birthday
       * </pre>
       *
       * <code>.Date birthday = 9;</code>
       * @return Whether the birthday field is set.
       */
      public boolean hasBirthday() {
        return birthdayBuilder_ != null || birthday_ != null;
      }
      /**
       * <pre>
       * birthday
       * </pre>
       *
       * <code>.Date birthday = 9;</code>
       * @return The birthday.
       */
      public DateOuterClass.Date getBirthday() {
        if (birthdayBuilder_ == null) {
          return birthday_ == null ? DateOuterClass.Date.getDefaultInstance() : birthday_;
        } else {
          return birthdayBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * birthday
       * </pre>
       *
       * <code>.Date birthday = 9;</code>
       */
      public Builder setBirthday(DateOuterClass.Date value) {
        if (birthdayBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          birthday_ = value;
          onChanged();
        } else {
          birthdayBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * birthday
       * </pre>
       *
       * <code>.Date birthday = 9;</code>
       */
      public Builder setBirthday(
          DateOuterClass.Date.Builder builderForValue) {
        if (birthdayBuilder_ == null) {
          birthday_ = builderForValue.build();
          onChanged();
        } else {
          birthdayBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * birthday
       * </pre>
       *
       * <code>.Date birthday = 9;</code>
       */
      public Builder mergeBirthday(DateOuterClass.Date value) {
        if (birthdayBuilder_ == null) {
          if (birthday_ != null) {
            birthday_ =
              DateOuterClass.Date.newBuilder(birthday_).mergeFrom(value).buildPartial();
          } else {
            birthday_ = value;
          }
          onChanged();
        } else {
          birthdayBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * birthday
       * </pre>
       *
       * <code>.Date birthday = 9;</code>
       */
      public Builder clearBirthday() {
        if (birthdayBuilder_ == null) {
          birthday_ = null;
          onChanged();
        } else {
          birthday_ = null;
          birthdayBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * birthday
       * </pre>
       *
       * <code>.Date birthday = 9;</code>
       */
      public DateOuterClass.Date.Builder getBirthdayBuilder() {
        
        onChanged();
        return getBirthdayFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * birthday
       * </pre>
       *
       * <code>.Date birthday = 9;</code>
       */
      public DateOuterClass.DateOrBuilder getBirthdayOrBuilder() {
        if (birthdayBuilder_ != null) {
          return birthdayBuilder_.getMessageOrBuilder();
        } else {
          return birthday_ == null ?
              DateOuterClass.Date.getDefaultInstance() : birthday_;
        }
      }
      /**
       * <pre>
       * birthday
       * </pre>
       *
       * <code>.Date birthday = 9;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          DateOuterClass.Date, DateOuterClass.Date.Builder, DateOuterClass.DateOrBuilder> 
          getBirthdayFieldBuilder() {
        if (birthdayBuilder_ == null) {
          birthdayBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              DateOuterClass.Date, DateOuterClass.Date.Builder, DateOuterClass.DateOrBuilder>(
                  getBirthday(),
                  getParentForChildren(),
                  isClean());
          birthday_ = null;
        }
        return birthdayBuilder_;
      }

      private java.util.List<person.address.AddressOuterClass.Address> addresses_ =
        java.util.Collections.emptyList();
      private void ensureAddressesIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          addresses_ = new java.util.ArrayList<person.address.AddressOuterClass.Address>(addresses_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          person.address.AddressOuterClass.Address, person.address.AddressOuterClass.Address.Builder, person.address.AddressOuterClass.AddressOrBuilder> addressesBuilder_;

      /**
       * <pre>
       * multiple addresses
       * </pre>
       *
       * <code>repeated .person.address.Address addresses = 10;</code>
       */
      public java.util.List<person.address.AddressOuterClass.Address> getAddressesList() {
        if (addressesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(addresses_);
        } else {
          return addressesBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * multiple addresses
       * </pre>
       *
       * <code>repeated .person.address.Address addresses = 10;</code>
       */
      public int getAddressesCount() {
        if (addressesBuilder_ == null) {
          return addresses_.size();
        } else {
          return addressesBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * multiple addresses
       * </pre>
       *
       * <code>repeated .person.address.Address addresses = 10;</code>
       */
      public person.address.AddressOuterClass.Address getAddresses(int index) {
        if (addressesBuilder_ == null) {
          return addresses_.get(index);
        } else {
          return addressesBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * multiple addresses
       * </pre>
       *
       * <code>repeated .person.address.Address addresses = 10;</code>
       */
      public Builder setAddresses(
          int index, person.address.AddressOuterClass.Address value) {
        if (addressesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressesIsMutable();
          addresses_.set(index, value);
          onChanged();
        } else {
          addressesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * multiple addresses
       * </pre>
       *
       * <code>repeated .person.address.Address addresses = 10;</code>
       */
      public Builder setAddresses(
          int index, person.address.AddressOuterClass.Address.Builder builderForValue) {
        if (addressesBuilder_ == null) {
          ensureAddressesIsMutable();
          addresses_.set(index, builderForValue.build());
          onChanged();
        } else {
          addressesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * multiple addresses
       * </pre>
       *
       * <code>repeated .person.address.Address addresses = 10;</code>
       */
      public Builder addAddresses(person.address.AddressOuterClass.Address value) {
        if (addressesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressesIsMutable();
          addresses_.add(value);
          onChanged();
        } else {
          addressesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * multiple addresses
       * </pre>
       *
       * <code>repeated .person.address.Address addresses = 10;</code>
       */
      public Builder addAddresses(
          int index, person.address.AddressOuterClass.Address value) {
        if (addressesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressesIsMutable();
          addresses_.add(index, value);
          onChanged();
        } else {
          addressesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * multiple addresses
       * </pre>
       *
       * <code>repeated .person.address.Address addresses = 10;</code>
       */
      public Builder addAddresses(
          person.address.AddressOuterClass.Address.Builder builderForValue) {
        if (addressesBuilder_ == null) {
          ensureAddressesIsMutable();
          addresses_.add(builderForValue.build());
          onChanged();
        } else {
          addressesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * multiple addresses
       * </pre>
       *
       * <code>repeated .person.address.Address addresses = 10;</code>
       */
      public Builder addAddresses(
          int index, person.address.AddressOuterClass.Address.Builder builderForValue) {
        if (addressesBuilder_ == null) {
          ensureAddressesIsMutable();
          addresses_.add(index, builderForValue.build());
          onChanged();
        } else {
          addressesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * multiple addresses
       * </pre>
       *
       * <code>repeated .person.address.Address addresses = 10;</code>
       */
      public Builder addAllAddresses(
          java.lang.Iterable<? extends person.address.AddressOuterClass.Address> values) {
        if (addressesBuilder_ == null) {
          ensureAddressesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, addresses_);
          onChanged();
        } else {
          addressesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * multiple addresses
       * </pre>
       *
       * <code>repeated .person.address.Address addresses = 10;</code>
       */
      public Builder clearAddresses() {
        if (addressesBuilder_ == null) {
          addresses_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          addressesBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * multiple addresses
       * </pre>
       *
       * <code>repeated .person.address.Address addresses = 10;</code>
       */
      public Builder removeAddresses(int index) {
        if (addressesBuilder_ == null) {
          ensureAddressesIsMutable();
          addresses_.remove(index);
          onChanged();
        } else {
          addressesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * multiple addresses
       * </pre>
       *
       * <code>repeated .person.address.Address addresses = 10;</code>
       */
      public person.address.AddressOuterClass.Address.Builder getAddressesBuilder(
          int index) {
        return getAddressesFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * multiple addresses
       * </pre>
       *
       * <code>repeated .person.address.Address addresses = 10;</code>
       */
      public person.address.AddressOuterClass.AddressOrBuilder getAddressesOrBuilder(
          int index) {
        if (addressesBuilder_ == null) {
          return addresses_.get(index);  } else {
          return addressesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * multiple addresses
       * </pre>
       *
       * <code>repeated .person.address.Address addresses = 10;</code>
       */
      public java.util.List<? extends person.address.AddressOuterClass.AddressOrBuilder> 
           getAddressesOrBuilderList() {
        if (addressesBuilder_ != null) {
          return addressesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(addresses_);
        }
      }
      /**
       * <pre>
       * multiple addresses
       * </pre>
       *
       * <code>repeated .person.address.Address addresses = 10;</code>
       */
      public person.address.AddressOuterClass.Address.Builder addAddressesBuilder() {
        return getAddressesFieldBuilder().addBuilder(
            person.address.AddressOuterClass.Address.getDefaultInstance());
      }
      /**
       * <pre>
       * multiple addresses
       * </pre>
       *
       * <code>repeated .person.address.Address addresses = 10;</code>
       */
      public person.address.AddressOuterClass.Address.Builder addAddressesBuilder(
          int index) {
        return getAddressesFieldBuilder().addBuilder(
            index, person.address.AddressOuterClass.Address.getDefaultInstance());
      }
      /**
       * <pre>
       * multiple addresses
       * </pre>
       *
       * <code>repeated .person.address.Address addresses = 10;</code>
       */
      public java.util.List<person.address.AddressOuterClass.Address.Builder> 
           getAddressesBuilderList() {
        return getAddressesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          person.address.AddressOuterClass.Address, person.address.AddressOuterClass.Address.Builder, person.address.AddressOuterClass.AddressOrBuilder> 
          getAddressesFieldBuilder() {
        if (addressesBuilder_ == null) {
          addressesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              person.address.AddressOuterClass.Address, person.address.AddressOuterClass.Address.Builder, person.address.AddressOuterClass.AddressOrBuilder>(
                  addresses_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          addresses_ = null;
        }
        return addressesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:person.Person)
    }

    // @@protoc_insertion_point(class_scope:person.Person)
    private static final person.PersonOuterClass.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new person.PersonOuterClass.Person();
    }

    public static person.PersonOuterClass.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      @java.lang.Override
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public person.PersonOuterClass.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_person_MyMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_person_MyMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_person_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_person_Person_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%protobuf_examples/protos/person.proto\022" +
      "\006person\032#protobuf_examples/protos/date.p" +
      "roto\032&protobuf_examples/protos/address.p" +
      "roto\"A\n\tMyMessage\022\n\n\002id\030\001 \001(\005\022\022\n\nfirst_n" +
      "ame\030\002 \001(\t\022\024\n\014is_validated\030\003 \001(\010\"\371\001\n\006Pers" +
      "on\022\013\n\003age\030\001 \001(\005\022\022\n\nfirst_name\030\002 \001(\t\022\021\n\tl" +
      "ast_name\030\003 \001(\t\022\025\n\rsmall_picture\030\004 \001(\014\022\023\n" +
      "\013is_verified\030\005 \001(\010\022\016\n\006height\030\006 \001(\002\022\025\n\rph" +
      "one_numbers\030\007 \003(\t\022#\n\teye_color\030\010 \001(\0162\020.p" +
      "erson.EyeColor\022\027\n\010birthday\030\t \001(\0132\005.Date\022" +
      "*\n\taddresses\030\n \003(\0132\027.person.address.Addr" +
      "ess*[\n\010EyeColor\022\024\n\020UNKNOW_EYE_COLOR\020\000\022\r\n" +
      "\tEYE_GREEN\020\001\022\r\n\tEYE_BROWN\020\002\022\014\n\010EYE_BLUE\020" +
      "\003\022\r\n\tEYE_BLACK\020\004b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          DateOuterClass.getDescriptor(),
          person.address.AddressOuterClass.getDescriptor(),
        });
    internal_static_person_MyMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_person_MyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_person_MyMessage_descriptor,
        new java.lang.String[] { "Id", "FirstName", "IsValidated", });
    internal_static_person_Person_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_person_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_person_Person_descriptor,
        new java.lang.String[] { "Age", "FirstName", "LastName", "SmallPicture", "IsVerified", "Height", "PhoneNumbers", "EyeColor", "Birthday", "Addresses", });
    DateOuterClass.getDescriptor();
    person.address.AddressOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
