// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf_examples/protos/address.proto

package person.address;

public final class AddressOuterClass {
  private AddressOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AddressOrBuilder extends
      // @@protoc_insertion_point(interface_extends:person.address.Address)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string address_line_1 = 1;</code>
     * @return The addressLine1.
     */
    java.lang.String getAddressLine1();
    /**
     * <code>string address_line_1 = 1;</code>
     * @return The bytes for addressLine1.
     */
    com.google.protobuf.ByteString
        getAddressLine1Bytes();

    /**
     * <code>string address_line_2 = 2;</code>
     * @return The addressLine2.
     */
    java.lang.String getAddressLine2();
    /**
     * <code>string address_line_2 = 2;</code>
     * @return The bytes for addressLine2.
     */
    com.google.protobuf.ByteString
        getAddressLine2Bytes();

    /**
     * <code>string zip_code = 3;</code>
     * @return The zipCode.
     */
    java.lang.String getZipCode();
    /**
     * <code>string zip_code = 3;</code>
     * @return The bytes for zipCode.
     */
    com.google.protobuf.ByteString
        getZipCodeBytes();

    /**
     * <code>string city = 4;</code>
     * @return The city.
     */
    java.lang.String getCity();
    /**
     * <code>string city = 4;</code>
     * @return The bytes for city.
     */
    com.google.protobuf.ByteString
        getCityBytes();

    /**
     * <code>string country = 5;</code>
     * @return The country.
     */
    java.lang.String getCountry();
    /**
     * <code>string country = 5;</code>
     * @return The bytes for country.
     */
    com.google.protobuf.ByteString
        getCountryBytes();
  }
  /**
   * Protobuf type {@code person.address.Address}
   */
  public static final class Address extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:person.address.Address)
      AddressOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Address.newBuilder() to construct.
    private Address(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Address() {
      addressLine1_ = "";
      addressLine2_ = "";
      zipCode_ = "";
      city_ = "";
      country_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Address();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Address(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              addressLine1_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              addressLine2_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              zipCode_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              city_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              country_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return person.address.AddressOuterClass.internal_static_person_address_Address_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return person.address.AddressOuterClass.internal_static_person_address_Address_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              person.address.AddressOuterClass.Address.class, person.address.AddressOuterClass.Address.Builder.class);
    }

    public static final int ADDRESS_LINE_1_FIELD_NUMBER = 1;
    private volatile java.lang.Object addressLine1_;
    /**
     * <code>string address_line_1 = 1;</code>
     * @return The addressLine1.
     */
    @java.lang.Override
    public java.lang.String getAddressLine1() {
      java.lang.Object ref = addressLine1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        addressLine1_ = s;
        return s;
      }
    }
    /**
     * <code>string address_line_1 = 1;</code>
     * @return The bytes for addressLine1.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAddressLine1Bytes() {
      java.lang.Object ref = addressLine1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        addressLine1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_LINE_2_FIELD_NUMBER = 2;
    private volatile java.lang.Object addressLine2_;
    /**
     * <code>string address_line_2 = 2;</code>
     * @return The addressLine2.
     */
    @java.lang.Override
    public java.lang.String getAddressLine2() {
      java.lang.Object ref = addressLine2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        addressLine2_ = s;
        return s;
      }
    }
    /**
     * <code>string address_line_2 = 2;</code>
     * @return The bytes for addressLine2.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAddressLine2Bytes() {
      java.lang.Object ref = addressLine2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        addressLine2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ZIP_CODE_FIELD_NUMBER = 3;
    private volatile java.lang.Object zipCode_;
    /**
     * <code>string zip_code = 3;</code>
     * @return The zipCode.
     */
    @java.lang.Override
    public java.lang.String getZipCode() {
      java.lang.Object ref = zipCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        zipCode_ = s;
        return s;
      }
    }
    /**
     * <code>string zip_code = 3;</code>
     * @return The bytes for zipCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getZipCodeBytes() {
      java.lang.Object ref = zipCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        zipCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITY_FIELD_NUMBER = 4;
    private volatile java.lang.Object city_;
    /**
     * <code>string city = 4;</code>
     * @return The city.
     */
    @java.lang.Override
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      }
    }
    /**
     * <code>string city = 4;</code>
     * @return The bytes for city.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COUNTRY_FIELD_NUMBER = 5;
    private volatile java.lang.Object country_;
    /**
     * <code>string country = 5;</code>
     * @return The country.
     */
    @java.lang.Override
    public java.lang.String getCountry() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        country_ = s;
        return s;
      }
    }
    /**
     * <code>string country = 5;</code>
     * @return The bytes for country.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCountryBytes() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        country_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAddressLine1Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, addressLine1_);
      }
      if (!getAddressLine2Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, addressLine2_);
      }
      if (!getZipCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, zipCode_);
      }
      if (!getCityBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, city_);
      }
      if (!getCountryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, country_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAddressLine1Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, addressLine1_);
      }
      if (!getAddressLine2Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, addressLine2_);
      }
      if (!getZipCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, zipCode_);
      }
      if (!getCityBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, city_);
      }
      if (!getCountryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, country_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof person.address.AddressOuterClass.Address)) {
        return super.equals(obj);
      }
      person.address.AddressOuterClass.Address other = (person.address.AddressOuterClass.Address) obj;

      if (!getAddressLine1()
          .equals(other.getAddressLine1())) return false;
      if (!getAddressLine2()
          .equals(other.getAddressLine2())) return false;
      if (!getZipCode()
          .equals(other.getZipCode())) return false;
      if (!getCity()
          .equals(other.getCity())) return false;
      if (!getCountry()
          .equals(other.getCountry())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ADDRESS_LINE_1_FIELD_NUMBER;
      hash = (53 * hash) + getAddressLine1().hashCode();
      hash = (37 * hash) + ADDRESS_LINE_2_FIELD_NUMBER;
      hash = (53 * hash) + getAddressLine2().hashCode();
      hash = (37 * hash) + ZIP_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getZipCode().hashCode();
      hash = (37 * hash) + CITY_FIELD_NUMBER;
      hash = (53 * hash) + getCity().hashCode();
      hash = (37 * hash) + COUNTRY_FIELD_NUMBER;
      hash = (53 * hash) + getCountry().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static person.address.AddressOuterClass.Address parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static person.address.AddressOuterClass.Address parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static person.address.AddressOuterClass.Address parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static person.address.AddressOuterClass.Address parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static person.address.AddressOuterClass.Address parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static person.address.AddressOuterClass.Address parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static person.address.AddressOuterClass.Address parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static person.address.AddressOuterClass.Address parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static person.address.AddressOuterClass.Address parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static person.address.AddressOuterClass.Address parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static person.address.AddressOuterClass.Address parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static person.address.AddressOuterClass.Address parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(person.address.AddressOuterClass.Address prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code person.address.Address}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:person.address.Address)
        person.address.AddressOuterClass.AddressOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return person.address.AddressOuterClass.internal_static_person_address_Address_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return person.address.AddressOuterClass.internal_static_person_address_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                person.address.AddressOuterClass.Address.class, person.address.AddressOuterClass.Address.Builder.class);
      }

      // Construct using person.address.AddressOuterClass.Address.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        addressLine1_ = "";

        addressLine2_ = "";

        zipCode_ = "";

        city_ = "";

        country_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return person.address.AddressOuterClass.internal_static_person_address_Address_descriptor;
      }

      @java.lang.Override
      public person.address.AddressOuterClass.Address getDefaultInstanceForType() {
        return person.address.AddressOuterClass.Address.getDefaultInstance();
      }

      @java.lang.Override
      public person.address.AddressOuterClass.Address build() {
        person.address.AddressOuterClass.Address result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public person.address.AddressOuterClass.Address buildPartial() {
        person.address.AddressOuterClass.Address result = new person.address.AddressOuterClass.Address(this);
        result.addressLine1_ = addressLine1_;
        result.addressLine2_ = addressLine2_;
        result.zipCode_ = zipCode_;
        result.city_ = city_;
        result.country_ = country_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof person.address.AddressOuterClass.Address) {
          return mergeFrom((person.address.AddressOuterClass.Address)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(person.address.AddressOuterClass.Address other) {
        if (other == person.address.AddressOuterClass.Address.getDefaultInstance()) return this;
        if (!other.getAddressLine1().isEmpty()) {
          addressLine1_ = other.addressLine1_;
          onChanged();
        }
        if (!other.getAddressLine2().isEmpty()) {
          addressLine2_ = other.addressLine2_;
          onChanged();
        }
        if (!other.getZipCode().isEmpty()) {
          zipCode_ = other.zipCode_;
          onChanged();
        }
        if (!other.getCity().isEmpty()) {
          city_ = other.city_;
          onChanged();
        }
        if (!other.getCountry().isEmpty()) {
          country_ = other.country_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        person.address.AddressOuterClass.Address parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (person.address.AddressOuterClass.Address) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object addressLine1_ = "";
      /**
       * <code>string address_line_1 = 1;</code>
       * @return The addressLine1.
       */
      public java.lang.String getAddressLine1() {
        java.lang.Object ref = addressLine1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          addressLine1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string address_line_1 = 1;</code>
       * @return The bytes for addressLine1.
       */
      public com.google.protobuf.ByteString
          getAddressLine1Bytes() {
        java.lang.Object ref = addressLine1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          addressLine1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address_line_1 = 1;</code>
       * @param value The addressLine1 to set.
       * @return This builder for chaining.
       */
      public Builder setAddressLine1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        addressLine1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string address_line_1 = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddressLine1() {
        
        addressLine1_ = getDefaultInstance().getAddressLine1();
        onChanged();
        return this;
      }
      /**
       * <code>string address_line_1 = 1;</code>
       * @param value The bytes for addressLine1 to set.
       * @return This builder for chaining.
       */
      public Builder setAddressLine1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        addressLine1_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object addressLine2_ = "";
      /**
       * <code>string address_line_2 = 2;</code>
       * @return The addressLine2.
       */
      public java.lang.String getAddressLine2() {
        java.lang.Object ref = addressLine2_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          addressLine2_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string address_line_2 = 2;</code>
       * @return The bytes for addressLine2.
       */
      public com.google.protobuf.ByteString
          getAddressLine2Bytes() {
        java.lang.Object ref = addressLine2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          addressLine2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address_line_2 = 2;</code>
       * @param value The addressLine2 to set.
       * @return This builder for chaining.
       */
      public Builder setAddressLine2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        addressLine2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string address_line_2 = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddressLine2() {
        
        addressLine2_ = getDefaultInstance().getAddressLine2();
        onChanged();
        return this;
      }
      /**
       * <code>string address_line_2 = 2;</code>
       * @param value The bytes for addressLine2 to set.
       * @return This builder for chaining.
       */
      public Builder setAddressLine2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        addressLine2_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object zipCode_ = "";
      /**
       * <code>string zip_code = 3;</code>
       * @return The zipCode.
       */
      public java.lang.String getZipCode() {
        java.lang.Object ref = zipCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          zipCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string zip_code = 3;</code>
       * @return The bytes for zipCode.
       */
      public com.google.protobuf.ByteString
          getZipCodeBytes() {
        java.lang.Object ref = zipCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          zipCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string zip_code = 3;</code>
       * @param value The zipCode to set.
       * @return This builder for chaining.
       */
      public Builder setZipCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        zipCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string zip_code = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearZipCode() {
        
        zipCode_ = getDefaultInstance().getZipCode();
        onChanged();
        return this;
      }
      /**
       * <code>string zip_code = 3;</code>
       * @param value The bytes for zipCode to set.
       * @return This builder for chaining.
       */
      public Builder setZipCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        zipCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object city_ = "";
      /**
       * <code>string city = 4;</code>
       * @return The city.
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string city = 4;</code>
       * @return The bytes for city.
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string city = 4;</code>
       * @param value The city to set.
       * @return This builder for chaining.
       */
      public Builder setCity(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        city_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string city = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCity() {
        
        city_ = getDefaultInstance().getCity();
        onChanged();
        return this;
      }
      /**
       * <code>string city = 4;</code>
       * @param value The bytes for city to set.
       * @return This builder for chaining.
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        city_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object country_ = "";
      /**
       * <code>string country = 5;</code>
       * @return The country.
       */
      public java.lang.String getCountry() {
        java.lang.Object ref = country_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          country_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string country = 5;</code>
       * @return The bytes for country.
       */
      public com.google.protobuf.ByteString
          getCountryBytes() {
        java.lang.Object ref = country_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          country_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string country = 5;</code>
       * @param value The country to set.
       * @return This builder for chaining.
       */
      public Builder setCountry(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        country_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string country = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCountry() {
        
        country_ = getDefaultInstance().getCountry();
        onChanged();
        return this;
      }
      /**
       * <code>string country = 5;</code>
       * @param value The bytes for country to set.
       * @return This builder for chaining.
       */
      public Builder setCountryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        country_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:person.address.Address)
    }

    // @@protoc_insertion_point(class_scope:person.address.Address)
    private static final person.address.AddressOuterClass.Address DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new person.address.AddressOuterClass.Address();
    }

    public static person.address.AddressOuterClass.Address getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Address>
        PARSER = new com.google.protobuf.AbstractParser<Address>() {
      @java.lang.Override
      public Address parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Address(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Address> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Address> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public person.address.AddressOuterClass.Address getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_person_address_Address_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_person_address_Address_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&protobuf_examples/protos/address.proto" +
      "\022\016person.address\"j\n\007Address\022\026\n\016address_l" +
      "ine_1\030\001 \001(\t\022\026\n\016address_line_2\030\002 \001(\t\022\020\n\010z" +
      "ip_code\030\003 \001(\t\022\014\n\004city\030\004 \001(\t\022\017\n\007country\030\005" +
      " \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_person_address_Address_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_person_address_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_person_address_Address_descriptor,
        new java.lang.String[] { "AddressLine1", "AddressLine2", "ZipCode", "City", "Country", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
